name: Breakpoint
on:
  workflow_dispatch:

jobs:
  breakpoint:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Breakpoint
        uses: namespacelabs/breakpoint-action@v0
        with:
          duration: 30m
          authorized-users: grahamc
