on:
  workflow_dispatch: # allows manual triggering

env:
  NIX_INSTALLER_NIX_PACKAGE_URL: "https://install.determinate.systems/determinate-nix/rev/a60c4dba1f1f14168f3669af5ece96c2425a880c/x86_64-linux"

jobs:
  lockfile:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: DeterminateSystems/nix-installer-action@push-ytslqpsuuxpk
        with:
          extra-conf: |
              extra-experimental-features = provenance
      - uses: DeterminateSystems/flakehub-cache-action@main


      - run: |
          set -x
          cat /etc/nix/nix.conf || true
          cat /etc/nix/nix.custom.conf || true
          nix config show
          nix build  -Lv --impure --expr 'derivation { name = "hello-${builtins.toString builtins.currentTime}"; system = "x86_64-linux"; builder = "/bin/sh"; args = ["-c" "echo $out; echo hi > $out" ]; }'
          nix provenance show ./result
          nix path-info --json ./result
