on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  DeterminateCI:
    uses: DeterminateSystems/ci/.github/workflows/workflow.yml@propagate-outputs
    permissions:
      id-token: "write"
      contents: "read"
    with:
      visibility: public
  boop:
    needs: DeterminateCI
    runs-on: ubuntu-latest
    env:
      OUTPUTS: ${{ toJson(needs.DeterminateCI.outputs) }}
    steps:
      - run: echo "$OUTPUTS"
