on:
  workflow_dispatch:
jobs:
  tests:
    runs-on: ubuntu-latest
    permissions:
      id-token: "write"
      contents: "read"
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: DeterminateSystems/determinate-nix-action@main
        with:
          extra-conf: |
            lazy-trees = true
            extra-substituters = https://cloud-scythe-labs.cachix.org
            extra-trusted-public-keys = cloud-scythe-labs.cachix.org-1:I+IM+x2gGlmNjUMZOsyHJpxIzmAi7XhZNmTVijGjsLw=
      - run: nix config show
      - uses: DeterminateSystems/magic-nix-cache-action@main
        with:
          use-gha-cache: true
          upstream-cache: https://cloud-scythe-labs.cachix.org
      - run: nix config show
      - run: curl 'http://127.0.0.1:37515/nix-cache-info?trusted=1&compression=zstd&parallel-compression=true&priority=1'
