on:
  workflow_dispatch: # allows manual triggering

jobs:
  lockfile:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: DeterminateSystems/nix-installer-action@main
        with:
          determinate: true
      - name: Breakpoint if tests failed
        uses: namespacelabs/breakpoint-action@v0
        with:
          duration: 30m
          authorized-users: grahamc

      - run: cat /etc/nix/nix.conf
        if: success() || failure()
      - run: cat /etc/nix/nix.custom.conf
        if: success() || failure()
      - run: nix config show
        if: success() || failure()
      - run: nix-store -r /nix/store/gdaqmq0yxg2z1687ymxg35hpxl4qhp8m-flake-iter-0.1.0
        if: success() || failure()
      - run: nix-collect-garbage
        if: success() || failure()
      - uses: DeterminateSystems/flakehub-cache-action@main
        if: success() || failure()
      - run: cat /etc/nix/nix.conf
        if: success() || failure()
      - run: cat /etc/nix/nix.custom.conf
        if: success() || failure()
      - run: nix-store -r /nix/store/gdaqmq0yxg2z1687ymxg35hpxl4qhp8m-flake-iter-0.1.0
        if: success() || failure()
