on:
  workflow_dispatch: # allows manual triggering

jobs:
  lockfile:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: DeterminateSystems/nix-installer-action@main
        with:
          determinate: true
      - run: cat /etc/nix/nix.conf
      - run: cat /etc/nix/nix.custom.conf
      - run: nix run  -vvvv https://flakehub.com/f/DeterminateSystems/flake-iter/0
      - run: nix-collect-garbage
      - uses: DeterminateSystems/flakehub-cache-action@main
      - run: cat /etc/nix/nix.conf
      - run: cat /etc/nix/nix.custom.conf
      - run: nix run  -vvvv https://flakehub.com/f/DeterminateSystems/flake-iter/0
