on:
  workflow_dispatch: # allows manual triggering

jobs:
  fhstatus:
    permissions:
      id-token: write # Authenticate against FlakeHub
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
        with:
          determinate: true
      - run: determinate-nixd status
      - run: nix run "github:DeterminateSystems/fh" -- status
      - run: nix run "https://flakehub.com/f/DeterminateSystems/fh/0.1" -- status
