on:
  workflow_dispatch:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: DeterminateSystems/nix-installer-action@main
      - name: Check Nix flake inputs
        uses: DeterminateSystems/flake-checker-action@nonzero-err
        with:
          fail-mode: true
