name: "Publish every Git push to main to FlakeHub"
on:
  workflow_dispatch:
jobs:
  flakehub-publish:
    runs-on: "ubuntu-latest"
    permissions:
      id-token: write # Authenticate against FlakeHub
      contents: read
    steps:
      - uses: "actions/checkout@v3"
      - uses: "DeterminateSystems/nix-installer-action@main"
      - run: nix show-config
      - uses: "DeterminateSystems/flakehub-push@main"
        id: push
        with:
          rolling: true
          name: grahamc/test5
          visibility: "private"
          source-pr: 168
      - run: |
          echo ${{ steps.push.outputs.flakeref }}
