name: "Push to FlakeHub (manual)"

on:
  push:
    tags:
      - 'v*.*.*'
       # - '^v[0-9]+\.[0-9]*[02468]+\.[0-9]+$' ?
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag to publish to FlakeHub"
        type: "string"
        required: true

jobs:
  push:
    runs-on: "ubuntu-22.04"
    permissions:
      id-token: "write"
      contents: "read"
    steps:
      - run: echo '${{ toJson(inputs) }}'
      - uses: "actions/checkout@v3"
        with:
          ref: ${{ inputs.tag == '' && '' || format('refs/tags/{0}', inputs.tag) }}
      - uses: "DeterminateSystems/nix-installer-action@main"
      - uses: "DeterminateSystems/flakehub-push@main"
        with:
          visibility: "public"
          tag: ${{ inputs.tag == '' && null || inputs.tag }}
