name: "Publish every Git push to main to FlakeHub"
on:
  push:
    branches:
      - "main"
jobs:
  flakehub-publish:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v3"
      - uses: "DeterminateSystems/nix-installer-action@main"
      - run: nix show-config
      - uses: "DeterminateSystems/flakehub-push@main"
        with:
          rolling: true
          name: grahamc/test4
          visibility: "unlisted"
