name: Context testing
on:
  push:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - labeled

  workflow_dispatch:

jobs:
  dump_contexts_to_log:
    strategy:
      matrix:
        a: [1, 2]
        b: [3, 4]
      
    runs-on: ubuntu-latest
    steps:
    - uses: actions/github-script@v7
      id: set-result
      with:
        script: |
          console.log(core.platform)
          console.log(core.platform.getDetails())
        result-encoding: string
    - name: Get result
      run: echo "${{steps.set-result.outputs.result}}"
