name: GitHub Script
on:
  workflow_dispatch:

jobs:
  dump_contexts_to_log:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@main
        id: set-result
        with:
          script: |
            console.log(core)
            console.log(core.platform.getDetails())
          result-encoding: string
      - name: Get result
        run: echo "${{steps.set-result.outputs.result}}"
