on:
  workflow_dispatch:
jobs:
  tests:
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: DeterminateSystems/nix-installer-action@curl-data
      - run: nix build ./hash-mismatch.nix
