on:
  workflow_dispatch:
  pull_request:
jobs:
  tests:
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: DeterminateSystems/nix-installer-action@curl-data
        with:
          determinate: true
      - run: nix build -f ./hash-mismatch.nix
