name: Try Lix in GHA
on:
  workflow_dispatch:
jobs:
  tests:
    runs-on: ubuntu-latest
    permissions:
      id-token: "write"
      contents: "read"
    env:
      ACTIONS_RUNNER_DEBUG: "true"
      ACTIONS_STEP_DEBUG: "true"
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: actions/cache@v3
        with:
          path: ~/lixcat
          key: determinatesystem-nix-installer-x86_64-linux-37b484b605499fdebf3e1c88d2ec4336
      - run: |
            set +e
            set -x
            ls ~/lixcat
            cat ~/lixcat
            cat ~/lixcat/*

      - uses: DeterminateSystems/nix-installer-action@main
        with:
          source-url: https://install.lix.systems/lix
      - run: |
            nix build "https://flakehub.com/f/DeterminateSystems/fh/0.1.9.tar.gz"
