on:
  workflow_dispatch: # allows manual triggering

jobs:
  lockfile:
    runs-on: ubuntu-latest
    steps:
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@diagnostics
        env:
          RUST_LOG: trace
        with:
          use-flakehub: false
          use-gha-cache: false
