on:
  workflow_dispatch:
jobs:
  tests:
    runs-on: ubuntu-latest
    permissions:
      id-token: "write"
      contents: "read"
    steps:
      - uses: DeterminateSystems/determinate-nix-action@v3
        with:
          extra-conf:
            lazy-trees = true
      - run: nix config show
