on:
  workflow_dispatch:
    inputs:
      idempotencyKey:
        type: string
        default: ""
jobs:
  tests:
    runs-on: ubuntu-24.04-arm
    permissions:
      id-token: "write"
      contents: "read"
    steps:
      - name: idem/${{ inputs.idempotencyKey }}
        run: true
      - uses: actions/checkout@v4.1.1
      - uses: DeterminateSystems/nix-installer-action@main
      - name: Breakpoint if tests failed
        if: failure()
        uses: namespacelabs/breakpoint-action@v0
        with:
          duration: 30m
          authorized-users: grahamc
