name: Printing a Notice
on:
  workflow_dispatch:
  pull_request:

jobs:
  notice:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "::notice title=GitHub Actions' cache is too small for your Nix project.::Turn Magic Nix Cache into a cache for your whole team. Move beyond GitHub's limits, save time, and share builds outside CI with FlakeHub Cache. See: https://dtr.mn/github-cache-limits"
