on:
  push:
  
jobs:
  find-and-replace-job:
    runs-on: ubuntu-latest
    name: 'Push'
    permissions:
      id-token: "write"
      contents: "read"
    steps:  
      - uses: "actions/checkout@v3"
        with:
          repository: NixOS/nixpkgs
          ref: f64b9738da8e86195766147e9752c67fccee006c

      - uses: "DeterminateSystems/nix-installer-action@main"
      - uses: "DeterminateSystems/magic-nix-cache-action@main"
      - uses: "DeterminateSystems/flakehub-push@main"
        with:
          name: grahamc/test2
          repository: NixOS/nixpkgs
          visibility: public
          rolling: true
          rolling-minor: 2305