on:
  - push
  - workflow_dispatch

jobs:
  find-and-replace-job:
    strategy:
        fail-fast: false
        matrix:
          include:
            - branch: nixos-unstable      
            - branch: nixos-unstable-small
            - branch: nixpkgs-unstable    
            - branch: nixos-23.05         
            - branch: nixos-23.05-small   
            - branch: nixpkgs-23.05-darwin
            - branch: nixos-22.11         
            - branch: nixos-22.11-small   
            - branch: nixpkgs-22.11-darwin

    runs-on: ubuntu-latest
    name: 'Push'
    permissions:
      id-token: "write"
      contents: "read"
    steps:

      - name: Flake name
        run: |
          echo "The replaced value is nixpkgs${{
          (
            (endsWith(matrix.branch, '-small') && '-small')
            || (endsWith(matrix.branch, '-darwin') && '-darwin')
            || ((matrix.branch == 'nixpkgs-unstable') && '-unstable')
            || ""
          )}}"

      - name: Version - Remove nixpkgs-
        uses: mad9000/actions-find-and-replace-string@3
        id: branch_no_nixpkgs_prefix
        with:
          source: ${{ matrix.branch }}
          find: 'nixpkgs-'
          replace: ''
      - name: Version - Remove nixos-
        uses: mad9000/actions-find-and-replace-string@3
        id: branch_no_nixos_prefix
        with:
          source: ${{ steps.branch_no_nixpkgs_prefix.outputs.value }}
          find: 'nixos-'
          replace: ''
      - name: Version - Remove -small
        uses: mad9000/actions-find-and-replace-string@3
        id: branch_no_small_suffix
        with:
          source: ${{ steps.branch_no_nixos_prefix.outputs.value }}
          find: '-small'
          replace: ''
      - name: Version - Remove -darwin
        uses: mad9000/actions-find-and-replace-string@3
        id: branch_no_darwin_suffix
        with:
          source: ${{ steps.branch_no_small_suffix.outputs.value }}
          find: '-darwin'
          replace: ''
      - name: Version - Remove `.`s
        uses: mad9000/actions-find-and-replace-string@3
        id: minor_string_approximate
        with:
          source: ${{ steps.branch_no_darwin_suffix.outputs.value }}
          find: '.'
          replace: ''
      - name: Version - Replace `unstable` with `1`
        uses: mad9000/actions-find-and-replace-string@3
        id: minor_version
        with:
          source: ${{ steps.minor_string_approximate.outputs.value }}
          find: 'unstable'
          replace: '1'


      - name: Get the final output
        run: echo "The replaced value is ${{ steps.minor_version.outputs.value }}"