on:
  workflow_dispatch:
jobs:
  tests:
    runs-on: ubuntu-latest
    permissions:
      id-token: "write"
      contents: "read"
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: DeterminateSystems/nix-installer-action@main
        with:
          source-tag: v0.33.0
          extra-conf: |
            experimental-features = configurable-impure-env
      - run: nix config show
      - run: cat /etc/nix/nix.conf
