

name: Run NixOS Tests and other VMs on GitHub Actions.
on:
  pull_request:
  workflow_dispatch:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    permissions:
      id-token: "write"
      contents: "read"
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - run: |
            nix build "https://flakehub.com/f/DeterminateSystems/fh/0.1.9.tar.gz"
