name: vm
on:
  pull_request:
  workflow_dispatch:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v3.3.0
      - uses: DeterminateSystems/nix-installer-action@kvm
      - run: |
            nix-build '<nixpkgs/nixos/tests/doas.nix>'
